# Generated by Django 5.0.1 on 2024-04-18 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('Feed', models.CharField(max_length=500)),
            ],
        ),
    ]
