# Generated by Django 5.0.1 on 2024-04-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Username',
            new_name='Name',
        ),
    ]
