# Generated by Django 5.0.1 on 2024-04-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_username_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='Username',
        ),
    ]
