# Generated by Django 5.0.1 on 2024-04-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_feedback_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
